package Vista;

/** 
    @author Grupo 15
    Luis Ezequiel Sosa
    Lucas Saidman
    Luca Rodrigaño
    Ignacio Rodriguez
**/

public class App extends javax.swing.JFrame {
    
    private VistaAlumno vistaAlumno;
    private VistaMaterias vistaMaterias;
    private VistaInscripcion vistaInscripcion;
    private VistaCargaNotas vistaCargaNotas;
    private VistaListarInscripciones vistaListarInscripciones;

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jmb_menu = new javax.swing.JMenuBar();
        jm_alumno = new javax.swing.JMenu();
        jmi_gestion_alumnos = new javax.swing.JMenuItem();
        jm_materia = new javax.swing.JMenu();
        jmi_gestion_materias = new javax.swing.JMenuItem();
        jm_registro = new javax.swing.JMenu();
        jmi_gestion_inscripciones = new javax.swing.JMenuItem();
        jmi_cargar_notas = new javax.swing.JMenuItem();
        jmi_lista_inscripciones = new javax.swing.JMenuItem();
        jm_salir = new javax.swing.JMenu();
        jmi_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setMinimumSize(new java.awt.Dimension(888, 585));
        Escritorio.setName(""); // NOI18N
        Escritorio.setPreferredSize(new java.awt.Dimension(1000, 700));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jm_alumno.setText("Alumno");

        jmi_gestion_alumnos.setText("Gestion Alumnos");
        jmi_gestion_alumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_gestion_alumnosActionPerformed(evt);
            }
        });
        jm_alumno.add(jmi_gestion_alumnos);

        jmb_menu.add(jm_alumno);

        jm_materia.setText("Materia");

        jmi_gestion_materias.setText("Gestion Materias");
        jmi_gestion_materias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_gestion_materiasActionPerformed(evt);
            }
        });
        jm_materia.add(jmi_gestion_materias);

        jmb_menu.add(jm_materia);

        jm_registro.setText("Registro");

        jmi_gestion_inscripciones.setText("Gestion Inscripciones");
        jmi_gestion_inscripciones.setToolTipText("");
        jmi_gestion_inscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_gestion_inscripcionesActionPerformed(evt);
            }
        });
        jm_registro.add(jmi_gestion_inscripciones);

        jmi_cargar_notas.setText("Cargar Notas");
        jmi_cargar_notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cargar_notasActionPerformed(evt);
            }
        });
        jm_registro.add(jmi_cargar_notas);

        jmi_lista_inscripciones.setText("Lista Inscripciones");
        jmi_lista_inscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_lista_inscripcionesActionPerformed(evt);
            }
        });
        jm_registro.add(jmi_lista_inscripciones);

        jmb_menu.add(jm_registro);

        jm_salir.setText("Salir");

        jmi_salir.setText("Salir");
        jmi_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_salirActionPerformed(evt);
            }
        });
        jm_salir.add(jmi_salir);

        jmb_menu.add(jm_salir);

        setJMenuBar(jmb_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_gestion_alumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_gestion_alumnosActionPerformed
        if(vistaAlumno == null || vistaAlumno.isClosed()){
            vistaAlumno = new Vista.VistaAlumno();
            Escritorio.add(vistaAlumno);
            vistaAlumno.setVisible(true);
        };                                           
    }//GEN-LAST:event_jmi_gestion_alumnosActionPerformed

    private void jmi_gestion_materiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_gestion_materiasActionPerformed
        if(vistaMaterias == null || vistaMaterias.isClosed()){
            vistaMaterias = new Vista.VistaMaterias();
            Escritorio.add(vistaMaterias);
            vistaMaterias.setVisible(true);
        };
    }//GEN-LAST:event_jmi_gestion_materiasActionPerformed

    private void jmi_gestion_inscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_gestion_inscripcionesActionPerformed
        if(vistaInscripcion == null || vistaInscripcion.isClosed()){
            vistaInscripcion = new Vista.VistaInscripcion();
            Escritorio.add(vistaInscripcion);
            vistaInscripcion.setVisible(true);
        };
    }//GEN-LAST:event_jmi_gestion_inscripcionesActionPerformed

    private void jmi_cargar_notasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cargar_notasActionPerformed
        if(vistaCargaNotas == null || vistaCargaNotas.isClosed()){
            vistaCargaNotas = new Vista.VistaCargaNotas();
            Escritorio.add(vistaCargaNotas);
            vistaCargaNotas.setVisible(true);
        };
    }//GEN-LAST:event_jmi_cargar_notasActionPerformed

    private void jmi_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmi_salirActionPerformed

    private void jmi_lista_inscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_lista_inscripcionesActionPerformed
        if(vistaListarInscripciones == null || vistaListarInscripciones.isClosed()){
            vistaListarInscripciones = new Vista.VistaListarInscripciones();
            Escritorio.add(vistaListarInscripciones);
            vistaListarInscripciones.setVisible(true);
        };
    }//GEN-LAST:event_jmi_lista_inscripcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu jm_alumno;
    private javax.swing.JMenu jm_materia;
    private javax.swing.JMenu jm_registro;
    private javax.swing.JMenu jm_salir;
    private javax.swing.JMenuBar jmb_menu;
    private javax.swing.JMenuItem jmi_cargar_notas;
    private javax.swing.JMenuItem jmi_gestion_alumnos;
    private javax.swing.JMenuItem jmi_gestion_inscripciones;
    private javax.swing.JMenuItem jmi_gestion_materias;
    private javax.swing.JMenuItem jmi_lista_inscripciones;
    private javax.swing.JMenuItem jmi_salir;
    // End of variables declaration//GEN-END:variables
}
