package Vista;

import Modelo.Alumno;
import Persistencia.alumnoData;
import Persistencia.inscripcionData;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/** 
    @author Grupo 15
    Luis Ezequiel Sosa
    Lucas Saidman
    Luca Rodrigaño
    Ignacio Rodriguez
**/

public class VistaListarInscripciones extends javax.swing.JInternalFrame {
    
    private final alumnoData alumnoDao = new alumnoData();
    private final inscripcionData inscDao = new inscripcionData();

    private List<Alumno> alumnosCombo = new ArrayList<>();
    private DefaultTableModel modelo;

    /**
     * Creates new form VistaListarInscripciones
     */
    public VistaListarInscripciones() {
        initComponents();
        
        modelo = (DefaultTableModel) tabla_inscripciones_alumno.getModel();
        tabla_inscripciones_alumno.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        cargarAlumnosEnCombo();

        cb_alumnos.addActionListener(e -> alumnoSeleccionado());
    }
    
    private void msg(String s) {
        JOptionPane.showMessageDialog(this, s);
    }

    private void error(Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    private String safe(Object o) {
        return (o == null) ? "" : String.valueOf(o);
    }

    private void limpiarTabla() {
        modelo.setRowCount(0);
    }

    private void cargarAlumnosEnCombo() {
        try {
            alumnosCombo = alumnoDao.listarTodos();

            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            for (Alumno a : alumnosCombo) {
                String etiqueta = a.getDni() + ", " + safe(a.getNombre()) + " " + safe(a.getApellido());
                model.addElement(etiqueta);
            }
            cb_alumnos.setModel(model);

            if (cb_alumnos.getItemCount() > 0) {
                cb_alumnos.setSelectedIndex(0);
                alumnoSeleccionado();
            } else {
                limpiarTabla();
            }

        } catch (SQLException e) {
            error(e);
            System.out.println("ERROR: " + e);
        }
    }

    private void alumnoSeleccionado() {
        int idx = cb_alumnos.getSelectedIndex();
        if (idx < 0 || idx >= alumnosCombo.size()) {
            limpiarTabla();
            return;
        }
        Alumno sel = alumnosCombo.get(idx);
        cargarTablaInscripciones(sel.getIdAlumno());
    }

    private void cargarTablaInscripciones(int idAlumno) {
        try {
            List<Object[]> filas = inscDao.listarInscripcionesPorAlumno(idAlumno);
            limpiarTabla();
            for (Object[] row : filas) {
                modelo.addRow(new Object[]{
                    safe(row[0]), safe(row[1]), safe(row[2]),
                    safe(row[3]), safe(row[4]), safe(row[5])
                });
            }
        } catch (SQLException e) {
            error(e);
            System.out.println("ERROR: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_lista_inscripciones = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        sp_tabla_inscripciones_alumno = new javax.swing.JScrollPane();
        tabla_inscripciones_alumno = new javax.swing.JTable();
        btn_salir = new javax.swing.JButton();
        cb_alumnos = new javax.swing.JComboBox<>();
        lb_alumno = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1000, 700));

        lb_titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lb_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_titulo.setText("Lista Inscripciones");

        tabla_inscripciones_alumno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabla_inscripciones_alumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellido", "Materia", "Cuatrimestre", "Año Inscripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sp_tabla_inscripciones_alumno.setViewportView(tabla_inscripciones_alumno);

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        lb_alumno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_alumno.setText("Alumno:");

        javax.swing.GroupLayout pnl_lista_inscripcionesLayout = new javax.swing.GroupLayout(pnl_lista_inscripciones);
        pnl_lista_inscripciones.setLayout(pnl_lista_inscripcionesLayout);
        pnl_lista_inscripcionesLayout.setHorizontalGroup(
            pnl_lista_inscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_lista_inscripcionesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cb_alumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299))
            .addGroup(pnl_lista_inscripcionesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnl_lista_inscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_tabla_inscripciones_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnl_lista_inscripcionesLayout.setVerticalGroup(
            pnl_lista_inscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_lista_inscripcionesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lb_titulo)
                .addGap(40, 40, 40)
                .addGroup(pnl_lista_inscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_alumnos, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(lb_alumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(sp_tabla_inscripciones_alumno, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_lista_inscripciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_lista_inscripciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        dispose();
    }//GEN-LAST:event_btn_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cb_alumnos;
    private javax.swing.JLabel lb_alumno;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JPanel pnl_lista_inscripciones;
    private javax.swing.JScrollPane sp_tabla_inscripciones_alumno;
    private javax.swing.JTable tabla_inscripciones_alumno;
    // End of variables declaration//GEN-END:variables
}
